[targets]

[targets:vars]
ansible_user=root
ansible_password=qw401hng
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="socat - PROXY:frp.spo.nn-projects.ru:%h:%p,proxyport=5000"
